### PR TITLE
Add .github files that ought to be present in all repos

### LINKED ISSUE #1963: [Housekeeping] Copy common .github files to `.github` repository
### Describe the issue

We have `.github` directories across all repos under Flyte org. If we have a single [`.github`](https://github.com/flyteorg/.github) repo under flyteorg, we can have all the common `.github` files under one roof.

### What if we do not do this?

Maintenance

### Related component(s)

_No response_

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### PR DESCRIPTION
**Pull request by samhita-alla**
Signed-off-by: Samhita Alla <aallasamhita@gmail.com>

Fixes https://github.com/flyteorg/flyte/issues/1963

### CODE REVIEW

**Comment by yindia** [comment]
@samhita-alla do we need issue template in all repository, It only use in flyte repo.

**Comment by samhita-alla** [comment]
> @samhita-alla do we need issue template in all repository, It only use in flyte repo.

Actually no. But having it in the main `.github` repo wouldn't do any harm.

**Comment by samhita-alla** [comment]
@EngHabu / @kumare3, can I get a +1?

**Comment by kumare3** [comment]
> @EngHabu / @kumare3, can I get a +1?

I don't have context

**Pull request merged**
